server:
  port: 9000
spring:
  profiles:
    active: "dev"
  datasource:
    schema: classpath*:database/schema.sql
    data: classpath*:database/data.sql
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jackson:
    serialization:
      fail-on-empty-beans: false
      write_dates_as_timestamps: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 1MB

email:
  username: hotelcaliforniaaaaa@gmail.com
  password: server12345
---

spring:
  profiles: dev

  datasource:
      username: sa
      password:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:hotel;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;
      platform: h2
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: true
        web-allow-others: true
aws:
  credentials:
    key: "${S3_KEY}"
    secret: "${S3_SECRET}"
  bucket: "${S3_BUCKET}"
